# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dwe_loader}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marek Kowalcze"]
  s.date = %q{2010-05-20}
  s.description = %q{Entry point for JAVA STDW engine. Allows to use STDW engine from any JRuby application.}
  s.email = %q{marek.kowalcze@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "lib/dwe/base_ruby_manager.rb",
     "lib/dwe/config.rb",
     "lib/dwe/engine.rb",
     "lib/dwe/loader.rb",
     "lib/dwe/utils.rb",
     "lib/dwe_loader.rb",
     "lib/java_class_loader.rb"
  ]
  s.homepage = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Entry point for JAVA STDW engine.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

